### ISSUE TITLE
Regsvr fails

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [Meitinger/iFilter4Archives#1]
It gives this error from elevated/admin command prompt:

![image](https://user-images.githubusercontent.com/46422834/236469524-0b2df8c0-494f-4b1b-bf37-f05fd703bdc6.png)

**Comment by meitinger** [comment]
Make sure that
- you are using the right regsvr32.exe for the target architecture (either the one in system32 for x64 or SysWOW64 for x86)
- the 7z DLL is present and also of the right architecture

If all checks out, please provide the version and architecture of your 7z DLL.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Yep got it working. It's working beautifully, even with Open Shell
